### ISSUE TITLE
[BE] express 셋팅

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/cashbook-5#11]
## 요구사항

 - express Generater 사용
```
$ Just use 'npx'
  Or
$ npm install -g express-generator-typescript
```
 - Sequelize 사용
 - OAuth  Passport 사용    
 (옵션 : 이후 Passport 제거)

## 개발방법
 - [폴더구조 : nodejs-project-structure](https://softwareontheroad.com/ideal-nodejs-project-structure/)

**Comment by peanut-lover** [comment]
ORM 사용관련 처리를 위해서 미리 서버 세팅을 해보겠습니다.

**Comment by peanut-lover** [comment]
간단한 작업만 완료했고 내일(7/27) 같이 구조살펴보고 해당 이슈는 닫아도될 것 같습니다.
