### ISSUE TITLE
[UX] UX 개선 사항 

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/cashbook-5#124]
## 요구사항

초기 메인화면에서 데이터가 없을 때 스낵바를 보여줄 필요가 있을까요?

이미 가계부 리스트에서 텍스트로 데이터가 없음을 나타내는데.

사용자에게 스낵바로 알릴 필요는 없는게 더 나은 UX가 되지않을까요?
@HanCheo

**Comment by peanut-lover** [comment]
프로필을 눌러서 결제 수단을 추가해주세요.

**Comment by peanut-lover** [comment]
가계부 추가시 음수를 넣는것 대신에 지출/수입 을 선택하는 radio박스 추가

**Comment by HanCheo** [comment]
스낵바는 빼셔두 됩니당 :)
