### ISSUE TITLE
[FE] Header 관련 UI/UX 컴포넌트 작업

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/cashbook-5#4]
## 요구사항

- Logo 를 표시한다.
- 중앙에 현재 월을 표시한다. 
- (option) 날짜 선택을 위해 DatePicker 를 만든다.
- 헤더의 가장 오른쪽에는 내역/달력/통계탭을 표시한다.
- (option)  FadeIn/out 

<img width="691" alt="스크린샷 2021-07-26 오후 4 52 45" src="https://user-images.githubusercontent.com/20085849/126953090-55243a4b-e579-461b-8b62-07d7f7dbd1f2.png">

## 개발방법
- 예상 완료 시간: 07/26 ~ 07/27 11:00
- 실제 종료 시간: 

우선 Tailwind css 를 적용해서 간단하게 구현하자.

## 다른 접근 방법

page 전환할 때 애니메이션 방식 결정
우선 fade in/out

## 주의할 점
date picker 너무 오래 걸리지않으면 좋겠다.

**Comment by HanCheo** [comment]
실제 종료 시간: 07/27 9:30
