### ISSUE TITLE
[bug] Ledgers data Type 변경 필요

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/cashbook-5#71]
## 요구사항
DB에 ledgers date 타입이 datetime으로 되어있어

생성시 2021-08-01 00:00:00으로 들어가지고
데이터 조회후 자바스크립트로 getDate할 경우 
현재일자로 가져와지는게 아니라 (현재일 - 1)로 가져와지는 현상

mysql에서는 date 형태로 저장되어 있으므로 select에서는 문제가 없음

## 개발방법
1. ledgers 테이블의 데이터 타입을 datetime 이아니라 date로 변환
2. 프론트 백엔드에서 ledger.date 타입을 string로 변환하여 사용할 필요가 있음.

## 주의할 점

**Comment by HanCheo** [comment]
변환한 데이터 형태

![image](https://user-images.githubusercontent.com/38929712/127948153-8dbf43f0-77db-4b7b-afe8-759750384b87.png)

**Comment by peanut-lover** [comment]
아하 DB 타입의 문제였군요. 이부분은 한철님이 PR 올릴때 반영해서 올려주실 수 있나요? @HanCheo

**Comment by HanCheo** [comment]
넵 :)
