### ISSUE TITLE
[BE] Mysql 포트 닫고 터널링이용

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/cashbook-5#80]
## 요구사항
ec2.포트 닫고 터널링이용

**Comment by peanut-lover** [comment]
혹시 해당 이슈 내용은 외부에서 db 를 접근하려고 터널링을 하는 걸 말하나요?

express 서버 localhost로 접근해서 터널링은 필요없어보이는데 어떠신가요? @HanCheo

**Comment by HanCheo** [comment]
아 맞네용 테스트할때만 필요하고 배포하면 필요없을듯
